version: '3.9'
services:
  spawn-service:
    build: spawn-service
    container_name: spawn
    ports:
      - "8082:8082"

  users-service:
    build: users-service
    container_name: users
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/subi/mongodb5/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped