mongo_db:
  name: 'usersdb'

spawn_api:
  host: '127.0.0.1'
  port: '8082'

http:
  host: 'localhost'
  port: ':8081'
  default_read_timeout: 5 #seconds
  default_write_timeout: 5 #seconds
  default_shutdown_timeout: 3 #seconds

logger:
  log_level: 'debug'
  rollbar_env: 'task_for_golang_dev'